### ISSUE TITLE
Minimum of tei fields to turn toggle off

### ISSUE THREAD

**Issue by alicefuzier** [wellcomecollection/catalogue-pipeline#1959]
For https://github.com/wellcomecollection/platform/issues/5118

- [x] history -> Production place and date (#1949)
- [x] incipit/explicit -> begins ends for each item (#1965)
- [x] colophon (https://github.com/wellcomecollection/catalogue-pipeline/pull/1963)
- [x] physical description (extent & support/ page count & material) (#1962 )
- [x] locus for items and parts (#1969 )
